# Generated by Django 3.2 on 2021-05-25 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone_number', models.IntegerField()),
                ('customer_subscription_date', models.DateTimeField()),
                ('customer_subscription_expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=30)),
                ('subscription_duration', models.CharField(max_length=50)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.IntegerField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=30)),
                ('workout_description', models.TextField()),
                ('workout_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_transaction_id', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('event_description', models.TextField()),
                ('event_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acquisition_date', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
                ('equipment_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.subscription'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
